### ISSUE TITLE
`GLIBCXX_3.4.20' not found (required by /tmp/codessh-code-server)

### ISSUE THREAD

**Issue by randyg3000** [cdr/sshcode#97] opened 2019-05-08 00:36 UTC
Using binary sshcode on MacOS (downloaded 5/7/2019) to install/connect on remote AWS RHEL 7 server... gets most of the way through installation before the following errors are recorded (system information follows):

2019-05-07 14:34:33 INFO	ensuring code-server is updated...
Warning: No xauth data; using fake authentication data for X11 forwarding.
+ mkdir -p /home/ec2-user/.local/share/code-server
+ cd /tmp
+ wget -N https://codesrv-ci.cdr.sh/latest-linux
--2019-05-08 00:34:40--  https://codesrv-ci.cdr.sh/latest-linux
Resolving codesrv-ci.cdr.sh (codesrv-ci.cdr.sh)... 104.27.132.26, 104.27.133.26, 2606:4700:30::681b:851a, ...
Connecting to codesrv-ci.cdr.sh (codesrv-ci.cdr.sh)|104.27.132.26|:443... connected.
HTTP request sent, awaiting response... 200 OK
Cookie coming from codesrv-ci.cdr.sh attempted to set domain to codesrv-ci.cdr.sh
Length: 94698820 (90M) [application/octet-stream]
Server file no newer than local file ‘latest-linux’ -- not retrieving.

+ '[' -f /tmp/codessh-code-server ']'
+ rm /tmp/codessh-code-server
+ ln latest-linux /tmp/codessh-code-server
+ chmod +x /tmp/codessh-code-server
2019-05-07 14:34:40 INFO	syncing settings
Warning: No xauth data; using fake authentication data for X11 forwarding.
building file list ... done

sent 200 bytes  received 20 bytes  29.33 bytes/sec
total size is 181  speedup is 0.82
2019-05-07 14:34:47 INFO	synced settings in 6.853521372s
2019-05-07 14:34:47 INFO	syncing extensions
Warning: No xauth data; using fake authentication data for X11 forwarding.
building file list ... done

sent 129600 bytes  received 20 bytes  17282.67 bytes/sec
total size is 93654944  speedup is 722.53
2019-05-07 14:34:54 INFO	synced extensions in 14.183814675s
2019-05-07 14:34:54 INFO	starting code-server...
/tmp/codessh-code-server: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/codessh-code-server)
/tmp/codessh-code-server: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/codessh-code-server)
/tmp/codessh-code-server: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/codessh-code-server)
2019-05-07 14:35:09 FATAL	code-server didn't start in time context deadline exceeded

$ uname -a
Linux ip-172-31-34-190.us-east-2.compute.internal 3.10.0-862.14.4.el7.x86_64 #1 SMP Fri Sep 21 09:07:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ hostnamectl
   Static hostname: ip-172-31-34-190.us-east-2.compute.internal
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 3bf4cbc4ae224ef186fbc9ebb614f06a
           Boot ID: 143dc016a29848679eb1b547f97930ba
    Virtualization: xen
  Operating System: Red Hat Enterprise Linux Server 7.6 (Maipo)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.6:GA:server
            Kernel: Linux 3.10.0-862.14.4.el7.x86_64
      Architecture: x86-64

**Comment by sreya92** [comment] 2019-05-08 00:40
This is a known issue, there should be a `--docker` flag arriving in the next few days that should allow you to circumvent this. It will basically mount your specified directory inside an ubuntu container and forward the necessary ports

**Comment by sreya92** [comment] 2019-05-08 00:40
duplicate of #77

**Comment by sreya92** [comment] 2019-05-08 00:40
If possible I recommend using Ubuntu 16.04 or later

**Comment by magick93** [comment] 2019-05-08 02:36
> If possible I recommend using Ubuntu 16.04 or later

Is this for the client (where the `sshcode` command is issued) or the server ?

**Comment by sreya92** [comment] 2019-05-08 02:36
The server

**Comment by Magistern** [comment] 2019-05-22 09:22
> If possible I recommend using Ubuntu 16.04 or later

I don't understand this recommendation, but then again, I'm not that tech savvy. Does this mean we cannot, at the moment, run sshcode from a mac?

**Comment by deansheather** [comment] 2019-06-16 11:07
@Magistern No, it just means you can't run sshcode against a server that doesn't have the required glibc ABI version.

Closing as duplicate of #77.

**Closed by deansheather** 2019-06-16 11:07 UTC
